2022-08-06T22:07:24,711 User install by explicit request
2022-08-06T22:07:24,796 Created temporary directory: /tmp/pip-ephem-wheel-cache-qbv0s3rw
2022-08-06T22:07:24,796 Created temporary directory: /tmp/pip-req-tracker-o7cumqqd
2022-08-06T22:07:24,796 Initialized build tracking at /tmp/pip-req-tracker-o7cumqqd
2022-08-06T22:07:24,796 Created build tracker: /tmp/pip-req-tracker-o7cumqqd
2022-08-06T22:07:24,797 Entered build tracker: /tmp/pip-req-tracker-o7cumqqd
2022-08-06T22:07:24,797 Created temporary directory: /tmp/pip-install-tnwrc4v_
2022-08-06T22:07:24,828 1 location(s) to search for versions of requirements.txt:
2022-08-06T22:07:24,828 * https://pypi.org/simple/requirements-txt/
2022-08-06T22:07:24,828 Fetching project page and analyzing links: https://pypi.org/simple/requirements-txt/
2022-08-06T22:07:24,828 Getting page https://pypi.org/simple/requirements-txt/
2022-08-06T22:07:24,829 Found index url https://pypi.org/simple
2022-08-06T22:07:24,830 Getting credentials from keyring for https://pypi.org/simple
2022-08-06T22:07:24,830 Getting credentials from keyring for pypi.org
2022-08-06T22:07:24,830 Looking up "https://pypi.org/simple/requirements-txt/" in the cache
2022-08-06T22:07:24,830 Request header has "max_age" as 0, cache bypassed
2022-08-06T22:07:24,831 Starting new HTTPS connection (1): pypi.org:443
2022-08-06T22:07:25,137 https://pypi.org:443 "GET /simple/requirements-txt/ HTTP/1.1" 404 13
2022-08-06T22:07:25,138 Status code 404 not in (200, 203, 300, 301)
2022-08-06T22:07:25,138 Could not fetch URL https://pypi.org/simple/requirements-txt/: 404 Client Error: Not Found for url: https://pypi.org/simple/requirements-txt/ - skipping
2022-08-06T22:07:25,140 Given no hashes to check 0 links for project 'requirements.txt': discarding no candidates
2022-08-06T22:07:25,140 ERROR: Could not find a version that satisfies the requirement requirements.txt (from versions: none)
2022-08-06T22:07:25,140 Cleaning up...
2022-08-06T22:07:25,140 Removed build tracker: '/tmp/pip-req-tracker-o7cumqqd'
2022-08-06T22:07:25,141 ERROR: No matching distribution found for requirements.txt
2022-08-06T22:07:25,141 Exception information:
2022-08-06T22:07:25,141 Traceback (most recent call last):
2022-08-06T22:07:25,141   File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 186, in _main
2022-08-06T22:07:25,141     status = self.run(options, args)
2022-08-06T22:07:25,141   File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 357, in run
2022-08-06T22:07:25,141     resolver.resolve(requirement_set)
2022-08-06T22:07:25,141   File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
2022-08-06T22:07:25,141     discovered_reqs.extend(self._resolve_one(requirement_set, req))
2022-08-06T22:07:25,141   File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
2022-08-06T22:07:25,141     abstract_dist = self._get_abstract_dist_for(req_to_install)
2022-08-06T22:07:25,141   File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 281, in _get_abstract_dist_for
2022-08-06T22:07:25,141     req.populate_link(self.finder, upgrade_allowed, require_hashes)
2022-08-06T22:07:25,141   File "/usr/lib/python3/dist-packages/pip/_internal/req/req_install.py", line 249, in populate_link
2022-08-06T22:07:25,141     self.link = finder.find_requirement(self, upgrade)
2022-08-06T22:07:25,141   File "/usr/lib/python3/dist-packages/pip/_internal/index/package_finder.py", line 926, in find_requirement
2022-08-06T22:07:25,141     raise DistributionNotFound(
2022-08-06T22:07:25,141 pip._internal.exceptions.DistributionNotFound: No matching distribution found for requirements.txt
2022-08-06T22:08:44,551 User install by explicit request
2022-08-06T22:08:44,626 Created temporary directory: /tmp/pip-ephem-wheel-cache-n8bfv_bx
2022-08-06T22:08:44,627 Created temporary directory: /tmp/pip-req-tracker-kzf65do2
2022-08-06T22:08:44,627 Initialized build tracking at /tmp/pip-req-tracker-kzf65do2
2022-08-06T22:08:44,627 Created build tracker: /tmp/pip-req-tracker-kzf65do2
2022-08-06T22:08:44,627 Entered build tracker: /tmp/pip-req-tracker-kzf65do2
2022-08-06T22:08:44,627 Created temporary directory: /tmp/pip-install-_kdd5h7w
2022-08-06T22:08:44,652 1 location(s) to search for versions of requirements.txt:
2022-08-06T22:08:44,652 * https://pypi.org/simple/requirements-txt/
2022-08-06T22:08:44,652 Fetching project page and analyzing links: https://pypi.org/simple/requirements-txt/
2022-08-06T22:08:44,653 Getting page https://pypi.org/simple/requirements-txt/
2022-08-06T22:08:44,653 Found index url https://pypi.org/simple
2022-08-06T22:08:44,656 Getting credentials from keyring for https://pypi.org/simple
2022-08-06T22:08:44,656 Getting credentials from keyring for pypi.org
2022-08-06T22:08:44,657 Looking up "https://pypi.org/simple/requirements-txt/" in the cache
2022-08-06T22:08:44,657 Request header has "max_age" as 0, cache bypassed
2022-08-06T22:08:44,658 Starting new HTTPS connection (1): pypi.org:443
2022-08-06T22:08:44,929 https://pypi.org:443 "GET /simple/requirements-txt/ HTTP/1.1" 404 13
2022-08-06T22:08:44,931 Status code 404 not in (200, 203, 300, 301)
2022-08-06T22:08:44,931 Could not fetch URL https://pypi.org/simple/requirements-txt/: 404 Client Error: Not Found for url: https://pypi.org/simple/requirements-txt/ - skipping
2022-08-06T22:08:44,932 Given no hashes to check 0 links for project 'requirements.txt': discarding no candidates
2022-08-06T22:08:44,932 ERROR: Could not find a version that satisfies the requirement requirements.txt (from versions: none)
2022-08-06T22:08:44,933 Cleaning up...
2022-08-06T22:08:44,933 Removed build tracker: '/tmp/pip-req-tracker-kzf65do2'
2022-08-06T22:08:44,933 ERROR: No matching distribution found for requirements.txt
2022-08-06T22:08:44,933 Exception information:
2022-08-06T22:08:44,933 Traceback (most recent call last):
2022-08-06T22:08:44,933   File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 186, in _main
2022-08-06T22:08:44,933     status = self.run(options, args)
2022-08-06T22:08:44,933   File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 357, in run
2022-08-06T22:08:44,933     resolver.resolve(requirement_set)
2022-08-06T22:08:44,933   File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
2022-08-06T22:08:44,933     discovered_reqs.extend(self._resolve_one(requirement_set, req))
2022-08-06T22:08:44,933   File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
2022-08-06T22:08:44,933     abstract_dist = self._get_abstract_dist_for(req_to_install)
2022-08-06T22:08:44,933   File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 281, in _get_abstract_dist_for
2022-08-06T22:08:44,933     req.populate_link(self.finder, upgrade_allowed, require_hashes)
2022-08-06T22:08:44,933   File "/usr/lib/python3/dist-packages/pip/_internal/req/req_install.py", line 249, in populate_link
2022-08-06T22:08:44,933     self.link = finder.find_requirement(self, upgrade)
2022-08-06T22:08:44,933   File "/usr/lib/python3/dist-packages/pip/_internal/index/package_finder.py", line 926, in find_requirement
2022-08-06T22:08:44,933     raise DistributionNotFound(
2022-08-06T22:08:44,933 pip._internal.exceptions.DistributionNotFound: No matching distribution found for requirements.txt
